# Generated by Django 5.2.4 on 2025-08-10 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_role_otp_expires_at_alter_otp_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_resources_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
