# Generated by Django 5.2.4 on 2025-08-11 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_resource_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_simulated_threat',
            field=models.BooleanField(default=False, help_text='Flag user as insider threat simulation'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='4', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'department')},
        ),
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('none', 'No Access')], max_length=10)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_controls', to='users.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
