# Generated by Django 5.2.4 on 2025-08-17 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_department_user_is_simulated_threat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='permission',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('download', 'Download'), ('delete', 'Delete'), ('upload', 'Upload'), ('none', 'No Access'), ('full_control', 'Full Access')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='access_level',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('download', 'Download'), ('delete', 'Delete'), ('upload', 'Upload'), ('none', 'No Access'), ('full_control', 'Full Access')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.department'),
        ),
    ]
