# Generated by Django 5.2.4 on 2025-08-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_department_user_is_simulated_threat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='IT', max_length=50),
        ),
    ]
