# Generated by Django 5.2.4 on 2025-08-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_accesscontrol_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
