# Generated by Django 5.2.4 on 2025-08-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_role_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='permission',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('download', 'Download'), ('delete', 'Delete'), ('upload', 'Upload'), ('none', 'No Access'), ('full_control', 'Full Access')], max_length=100),
        ),
    ]
