# Generated by Django 5.2.4 on 2025-08-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='access_level',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('download', 'Download'), ('delete', 'Delete'), ('upload', 'Upload'), ('none', 'No Access'), ('full_control', 'Full Access')], max_length=20),
        ),
    ]
