# Generated by Django 5.2.4 on 2025-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_resourceaccess_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='permissions',
            field=models.JSONField(default=dict),
        ),
    ]
