# Generated by Django 5.2.4 on 2025-08-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_resource_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='permission_string',
            field=models.TextField(default=''),
        ),
    ]
