# Generated by Django 5.2.4 on 2025-08-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_otp_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='department',
            field=models.CharField(choices=[('finance_department', 'Finance Department'), ('hr_department', 'Human Resources Department'), ('it_department', 'Information Technology Department'), ('marketing_department', 'Marketing Department'), ('operations_department', 'Operations Department')], default='not_assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='role',
            field=models.CharField(choices=[('finance_manager', 'Finance Manager'), ('accountant', 'Accountant'), ('financial_analyst', 'Financial Analyst'), ('auditor', 'Auditor'), ('CFO', 'Cfo'), ('HR_manager', 'Hr Manager'), ('recruiter', 'Recruiter'), ('payroll_specialist', 'Payroll Specialist'), ('HR_analyst', 'Hr Analyst'), ('CPO', 'Cpo'), ('IT_manager', 'It Manager'), ('system_administrator', 'System Administrator'), ('network_engineer', 'Network Engineer'), ('security_specialist', 'Security Specialist'), ('CTO', 'Cto'), ('marketing_manager', 'Marketing Manager'), ('content_creator', 'Content Creator'), ('SEO_specialist', 'Seo Specialist'), ('social_media_manager', 'Social Media Manager'), ('CMO', 'Cmo'), ('operations_manager', 'Operations Manager'), ('logistics_coordinator', 'Logistics Coordinator'), ('supply_chain_analyst', 'Supply Chain Analyst'), ('warehouse_supervisor', 'Warehouse Supervisor'), ('COO', 'Coo')], default='not_assigned', max_length=100),
        ),
    ]
