# Generated by Django 5.2.4 on 2025-08-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_employeedetails_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='classification_level',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('secret', 'Secret')], default='public', max_length=50),
        ),
    ]
