# Generated by Django 5.2.4 on 2025-08-07 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_rename_name_resource_resource'),
        ('rules_and_detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='policy_name',
            field=models.CharField(default='Default Policy', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='policy_type',
            field=models.CharField(choices=[('RBAC', 'Role-Based Access Control'), ('MAC', 'Mandatory Access Control'), ('DAC', 'Discretionary Access Control'), ('CUSTOM', 'Custom Policy')], default='RBAC', max_length=50),
        ),
        migrations.AlterField(
            model_name='accesspolicy',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accesspolicy',
            name='resource_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_policies_id', to='resources.resource'),
        ),
        migrations.AlterField(
            model_name='accesspolicy',
            name='resource_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_policies_name', to='resources.resource'),
        ),
    ]
