# Generated by Django 5.2.4 on 2025-08-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='resource',
        ),
    ]
