# Generated by Django 5.2.4 on 2025-08-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
